# Generated by Django 5.2.4 on 2025-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff')], default='guest', max_length=10),
        ),
    ]
